const doctors=[
{id:"DOC001",name:"Dr. Anjali Rao",specialization:"Cardiology",department:"Cardiology",contact:"9876543210",email:"anjali.rao@hospital.com",status:"current",login:"09:00 AM",logout:"05:00 PM",lastLogin:"29 Aug 2026, 09:00 AM",lastActive:"29 Aug 2026, 02:20 PM",emergency:"No",history:[["29 Aug 2026","09:00 AM","—","Active"],["28 Aug 2026","09:05 AM","05:02 PM","Completed"]]},
{id:"DOC002",name:"Dr. Rahul Mehta",specialization:"Neurology",department:"Neurology",contact:"9876543211",email:"rahul.mehta@hospital.com",status:"current",login:"08:45 AM",logout:"04:30 PM",lastLogin:"29 Aug 2026, 08:45 AM",lastActive:"29 Aug 2026, 02:10 PM",emergency:"No",history:[["29 Aug 2026","08:45 AM","—","Active"],["28 Aug 2026","08:50 AM","04:35 PM","Completed"]]},
{id:"DOC003",name:"Dr. Priya Shah",specialization:"Pediatrics",department:"Pediatrics",contact:"9876543212",email:"priya.shah@hospital.com",status:"current",login:"10:00 AM",logout:"06:00 PM",lastLogin:"29 Aug 2026, 10:00 AM",lastActive:"29 Aug 2026, 02:15 PM",emergency:"No",history:[["29 Aug 2026","10:00 AM","—","Active"],["28 Aug 2026","09:55 AM","06:00 PM","Completed"]]},
{id:"DOC004",name:"Dr. Vikram Singh",specialization:"Emergency Medicine",department:"Emergency",contact:"9876543213",email:"vikram.singh@hospital.com",status:"sos",login:"01:00 PM",logout:"—",lastLogin:"29 Aug 2026, 01:00 PM",lastActive:"29 Aug 2026, 02:25 PM",emergency:"YES",history:[["29 Aug 2026","01:00 PM","—","SOS Active"],["28 Aug 2026","02:00 PM","10:00 PM","Completed"]]},
{id:"DOC005",name:"Dr. Neha Gupta",specialization:"General Medicine",department:"General Medicine",contact:"9876543214",email:"neha.gupta@hospital.com",status:"past",login:"09:10 AM",logout:"05:05 PM",lastLogin:"28 Aug 2026, 09:10 AM",lastActive:"28 Aug 2026, 05:05 PM",emergency:"No",history:[["28 Aug 2026","09:10 AM","05:05 PM","Completed"],["27 Aug 2026","09:00 AM","05:00 PM","Completed"]]},
{id:"DOC006",name:"Dr. Arjun Patel",specialization:"Orthopedics",department:"Orthopedics",contact:"9876543215",email:"arjun.patel@hospital.com",status:"past",login:"08:30 AM",logout:"04:30 PM",lastLogin:"27 Aug 2026, 08:30 AM",lastActive:"27 Aug 2026, 04:30 PM",emergency:"No",history:[["27 Aug 2026","08:30 AM","04:30 PM","Completed"],["26 Aug 2026","08:40 AM","04:35 PM","Completed"]]}
];
let currentCategory="current";
function updateCounts(){for(const s of ["current","past","sos"])document.getElementById(s+"Count").textContent=String(doctors.filter(d=>d.status===s).length).padStart(2,"0")}
function selectCategory(c){currentCategory=c;document.querySelectorAll(".category").forEach(x=>x.classList.remove("selected"));document.getElementById(c+"Card").classList.add("selected");document.getElementById("searchInput").value="";displayDoctors()}
function displayDoctors(text=""){let a=doctors.filter(d=>d.status===currentCategory),q=text.toLowerCase().trim();if(q)a=a.filter(d=>[d.name,d.specialization,d.department,d.contact].some(v=>v.toLowerCase().includes(q)));let title={current:"Current Available Doctors",past:"Past Doctors",sos:"SOS Doctors"}[currentCategory];document.getElementById("tableTitle").textContent=title;document.getElementById("doctorCount").textContent=a.length+" doctor(s)";let t=document.getElementById("doctorTable");t.innerHTML="";if(!a.length){t.innerHTML='<tr><td colspan="7" class="empty">No doctors found.</td></tr>';return}a.forEach(d=>{let s=d.status==="current"?'<span class="status status-available">● Available</span>':d.status==="past"?'<span class="status status-past">● Past</span>':'<span class="status status-sos">● SOS</span>';t.insertAdjacentHTML("beforeend",`<tr><td class="doctor-name">👨‍⚕️ ${d.name}</td><td>${d.specialization}</td><td>${d.department}</td><td>${d.contact}</td><td>${s}</td><td>${d.login}</td><td><button class="view-button" onclick="viewDoctor('${d.id}')">View Details</button></td></tr>`)})}
document.getElementById("searchInput").addEventListener("input",e=>displayDoctors(e.target.value));
function viewDoctor(id){let d=doctors.find(x=>x.id===id);if(!d)return;document.getElementById("listPage").style.display="none";document.getElementById("detailsPage").style.display="block";for(const [id,val] of [["detailName",d.name],["detailName2",d.name],["detailSpecialization",d.specialization],["detailSpec",d.specialization],["detailDepartment",d.department],["detailID",d.id],["detailPhone",d.contact],["detailEmail",d.email],["detailLogin",d.login],["detailLogout",d.logout],["detailLastLogin",d.lastLogin],["detailLastActive",d.lastActive],["detailEmergency",d.emergency]])document.getElementById(id).textContent=val;document.getElementById("contactButton").href="tel:"+d.contact;let av=d.status==="current"?"🟢 Currently Available":d.status==="past"?"🟡 Not Currently Available":"🔴 SOS Active";document.getElementById("detailAvailability").textContent=av;let b=document.getElementById("detailStatus");b.className="status "+(d.status==="current"?"status-available":d.status==="past"?"status-past":"status-sos");b.textContent=d.status==="current"?"● AVAILABLE":d.status==="past"?"● PAST DOCTOR":"● SOS ACTIVE";document.getElementById("sosWarning").style.display=d.status==="sos"?"block":"none";let h=document.getElementById("historyTable");h.innerHTML="";d.history.forEach(r=>{let c=r[3]==="SOS Active"?"status-sos":r[3]==="Active"?"status-available":"status-past";h.insertAdjacentHTML("beforeend",`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${c}">● ${r[3]}</span></td></tr>`)})}
function goBack(){document.getElementById("detailsPage").style.display="none";document.getElementById("listPage").style.display="block"}
updateCounts();displayDoctors();
