const patient={name:'John Morgan',age:67};
const reports=[['MRI Report','12 Aug 2026','No acute abnormality'],['Blood Test','03 Aug 2026','Results within expected range'],['X-Ray','21 Jul 2026','No fracture identified']];
const payments=[['TXN-842195','12 Aug 2026','HDFC Bank •••• 4921','Green Valley Hospital','Cardiology consultation','₹1,250.00'],['TXN-841703','06 Aug 2026','ICICI Bank •••• 2108','Green Valley Hospital','Diagnostic tests','₹3,600.00'],['TXN-839624','29 Jul 2026','HDFC Bank •••• 4921','Care Pharmacy','Prescription medicines','₹825.00']];
const content=document.querySelector('#content'), crumb=document.querySelector('#crumb');
const page=(title,copy,html)=>`<div class="title"><p class="eyebrow">PATIENT CARE</p><h1>${title}</h1><p>${copy}</p></div>${html}`;
function render(tab){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));crumb.textContent=document.querySelector(`[data-tab="${tab}"] span`).textContent;
if(tab==='overview')content.innerHTML=page(`Good morning, ${patient.name.split(' ')[0]}.`,'Here is a simple overview of your care and health records.',`<div class="summary"><div class="card"><p>Current diagnosis</p><strong>Stable</strong><small>Last reviewed 12 Aug 2026</small></div><div class="card"><p>Upcoming appointment</p><strong>30 Aug</strong><small>Dr. Smith · 4:00 PM</small></div><div class="card"><p>Amount due</p><strong>₹4,850</strong><small>Due by 18 Aug 2026</small></div></div><div class="panel"><h2>Quick access</h2><p>Choose an area to see your information.</p><div class="list"><div class="item"><span class="icon">▤</span><span><strong>Your latest report is ready</strong><small>MRI Report · 12 Aug 2026</small></span><button data-go="reports">View report →</button></div><div class="item"><span class="icon">✦</span><span><strong>Need help with your care?</strong><small>Ask the healthcare assistant anytime.</small></span><button id="openChat">Open chat →</button></div></div></div>`);
if(tab==='reports')content.innerHTML=page('Past reports','Your medical reports are protected and available to review.',`<div class="panel"><h2>Medical reports</h2><div class="list">${reports.map(r=>`<div class="item"><span class="icon">▤</span><span><strong>${r[0]}</strong><small>${r[1]} · ${r[2]}</small></span><button>View report →</button></div>`).join('')}</div></div>`);
if(tab==='diagnosis')content.innerHTML=page('Current diagnosis','Your latest care plan and clinical notes.',`<div class="panel diagnosis"><span class="tag">CURRENT CARE PLAN</span><h2>Hypertension · monitored</h2><p>Your latest assessment indicates stable blood pressure with the current treatment plan.</p><div class="list"><div class="item"><span class="icon">✓</span><span><strong>Continue prescribed medication</strong><small>Take medication as directed by Dr. Smith.</small></span></div><div class="item"><span class="icon">◷</span><span><strong>Follow-up consultation</strong><small>30 Aug 2026 · 4:00 PM</small></span></div></div></div>`);
if(tab==='doctors')content.innerHTML=page('Doctor details','Your current care team and contact details.',`<div class="doctor-grid"><div class="panel doctor"><div class="avatar">DS</div><h3>Dr. Ava Smith</h3><p>Cardiologist · Green Valley Hospital</p><div class="list"><div class="item"><span class="icon">☎</span><span><strong>+91 00000 00000</strong><small>Mock contact number</small></span></div></div></div><div class="panel doctor"><div class="avatar">RK</div><h3>Dr. Rohan Kapoor</h3><p>General Physician · Green Valley Hospital</p><div class="list"><div class="item"><span class="icon">◷</span><span><strong>Next available slot</strong><small>02 Sep 2026 · 10:30 AM</small></span></div></div></div></div>`);
if(tab==='payments')content.innerHTML=page('Payments & billing','Review your healthcare expenses and payment history.',`<div class="summary"><div class="card"><p>Amount due</p><strong>₹4,850</strong><small>Due by 18 Aug 2026</small></div><div class="card"><p>Paid this year</p><strong>₹26,750</strong><small>Across 12 transactions</small></div><div class="card"><p>Insurance covered</p><strong>₹18,400</strong><small>68.8% of total bills</small></div></div><div class="panel"><h2>Recent transactions</h2><table><thead><tr><th>TRANSACTION ID</th><th>DATE</th><th>MADE FROM</th><th>MADE TO</th><th>PURPOSE</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>${payments.map(p=>`<tr>${p.map(x=>`<td>${x}</td>`).join('')}<td><span class="status">Paid</span></td></tr>`).join('')}</tbody></table></div>`);
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>render(x.dataset.go));document.querySelector('#openChat')?.addEventListener('click',openChat)}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>render(x.dataset.tab));
const bot=document.querySelector('#chatbot'),messages=document.querySelector('#messages');function add(text,kind='bot'){const m=document.createElement('div');m.className=`message ${kind}`;m.textContent=text;messages.append(m);messages.scrollTop=messages.scrollHeight}function openChat(){bot.classList.add('open');if(!messages.children.length)add(`Hello ${patient.name.split(' ')[0]}! I’m your healthcare assistant. How can I help you today?`)}document.querySelector('#chatOpen').onclick=openChat;document.querySelector('#chatClose').onclick=()=>bot.classList.remove('open');function answer(q){const t=q.toLowerCase();if(t.includes('report'))return 'Your reports are in the Past reports tab. Your latest MRI report is dated 12 Aug 2026.';if(t.includes('payment'))return 'You have ₹4,850 due. Your payment history is available in the Payments tab.';if(t.includes('prescription'))return 'Your mock prescription includes Metformin 500 mg and Vitamin D3. For any change, please contact your doctor.';if(t.includes('doctor'))return 'Dr. Ava Smith is your cardiologist. Her details are in the Doctor details tab.';return 'I can help you find reports, prescriptions, doctor details, appointments, and payment information.'}document.querySelector('#chatForm').onsubmit=e=>{e.preventDefault();const q=document.querySelector('#chatInput').value.trim();if(!q)return;add(q,'user');document.querySelector('#chatInput').value='';setTimeout(()=>add(answer(q)),350)};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{document.querySelector('#chatInput').value=b.textContent;document.querySelector('#chatForm').requestSubmit()});render('overview');
